//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devexpress_Technical_Project_Web.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbTeknikServisEntities : DbContext
    {
        public DbTeknikServisEntities()
            : base("name=DbTeknikServisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblÜrünTakip> TblÜrünTakip { get; set; }
        public virtual DbSet<TblHakkımızda> TblHakkımızda { get; set; }
        public virtual DbSet<TblÜrün> TblÜrün { get; set; }
        public virtual DbSet<TblMesaj> TblMesaj { get; set; }
    }
}
