//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devexpress_Technical_Project_Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblHakkımızda
    {
        public byte ID { get; set; }
        public string Hakkımızda { get; set; }
    }
}
