//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devexpress_Technical_Project_Web.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblÜrünTakip
    {
        public int TakipID { get; set; }
        public string Açıklama { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string SeriNo { get; set; }
    }
}
